### ISSUE TITLE
Create Mongoose Schemas

### ISSUE THREAD

**Issue by johnbwoodruff** [jbw91/scheduling-hero-api#10]
Schemas needed:
- User
- Request
- Response?

As we think of more we can add them here.

**Comment by drewdaemon** [comment]
@jbw91 user could look something like:

```
{
    id: String,
    date_created: Date, //not necessarily critical, but could be interesting from a growth analysis perspective
    email: String,
    requests: [ String ], // request ids 
    responses: [ String ] // response ids
}
```

It seems pretty simple.  Is there something I'm missing?

**Comment by drewdaemon** [comment]
And actually, I'm trying to learn to think with the **noSQL paradigm**.  Maybe instead of trying to create three different collections and linking them together with ids (that sounds relational) we'd have a collection of user documents that contain all responses and requests inside of them:

```
{
    id: String,
    data_created: Date,
    email: String,
    requests [{
            id: String,
            target_date: Date,
            responses: [{
                id: String,
                user_id: String,
                // not sure how we'll store the actual response data--times available, etc
                // we can probably design that best once we understand Google calendar's api
            }]
    }]
}
```

Thoughts?  @jbw91 @mountain01 @gshigeto @sttracy4

**Comment by johnbwoodruff** [comment]
I would definitely have brought this up if you hadn't yourself. I'm not sure if we'd want to have the requests and responses inside of a user, we could probably have a user collection and then a requests collection which we can query by username/id. Although I could definitely see us keeping the requests inside of a user, I don't initially think that would be problematic. We could run some benchmarks when we've got something put together. But definitely having responses inside of the requests is better. Responses never need to be standalone.

**Comment by johnbwoodruff** [comment]
Leaving this issue open for now because there is still need to define the response object, plus verify that we don't want other attributes on a user.

**Comment by johnbwoodruff** [comment]
@drewctate @mountain01 @sttracy4 @gshigeto suddenly not sure about having the requests and responses inside of a user. Maybe something more like this?

``` json
/* User Collection */
{
  "userId": "String",
  "username": "String",
  "dateCreated": "Date",
  "email": "String"
}

/* Requests Collection */
{
  "userId": "String",
  "dateCreated": "Date",
  "targetStartDate": "Date",
  "targetEndDate": "Date",
  "title": "String",
  "description": "String",
  "location": "String",
  "invitees": ["String"],
  "responses": []
}
```

Because we don't want to get back the whole user every time for every request. I think that's overkill. What do you all think?
