### ISSUE TITLE
Use TypeScript in this project

### ISSUE THREAD

**Issue by johnbwoodruff** [jbw91/scheduling-hero-api#11]
Obviously for the frontend we'll be using TypeScript and Angular 2. That brings up the question, should we also write the backend in TypeScript? We would get lots of good benefits, the least of which include Intellisense during development and the ability to use more strongly typed code with interfaces and such. However, would that be overkill in this case? It'd definitely be easier to just use ES5, not to mention documentation is more sparse with TypeScript and Node.js projects.

Anyway, I don't have a particular opinion in mind, I'm hoping to get some discussion going. @drewctate, @mountain01, @sttracy4, @gshigeto, thoughts?

**Comment by johnbwoodruff** [comment]
Some other thoughts I had...

**Cons:**
- There may not be type definitions for all the node libraries we want to use. (from DefinitelyTyped or elsewhere) That would hurt the benefit of intellisense.
- There is the chance that we would have to again mess with the development and remote debugging inside a container to have it include TypeScript compiling upon saving PLUS the nodemon reload. If this project gets big, it could get slow.

**Comment by drewdaemon** [comment]
My initial tendency is to keep our typescript to the front end.  We'll already be gaining typescript experience on the front end like @jbw91 says, and it just seems like it would be nice to gain experience deving in pure Node.  I also think that typescript might be overkill for an app this small.  But, I'm definitely open to changing my perspective.

**Comment by johnbwoodruff** [comment]
I think that sounds good to me. Nobody else seems to have an opinion, so let's just keep it to ES5 for now!
